// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sol3.Data.SQL.Weather;

namespace Sol3.Data.SQL.Weather.Migrations
{
    [DbContext(typeof(WeatherContext))]
    partial class WeatherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sol3.Data.SQL.Weather.Models.Cloud", b =>
                {
                    b.Property<Guid>("WeatherResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("All")
                        .HasColumnType("int");

                    b.HasKey("WeatherResponseId");

                    b.ToTable("Cloud");
                });

            modelBuilder.Entity("Sol3.Data.SQL.Weather.Models.Coord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<Guid>("WeatherResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WeatherResponseId")
                        .IsUnique();

                    b.ToTable("Coords");
                });

            modelBuilder.Entity("Sol3.Data.SQL.Weather.Models.Main", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<double>("FeelsLike")
                        .HasColumnType("float");

                    b.Property<int>("GrndLevel")
                        .HasColumnType("int");

                    b.Property<int>("Humidity")
                        .HasColumnType("int");

                    b.Property<int>("Pressure")
                        .HasColumnType("int");

                    b.Property<int>("SeaLevel")
                        .HasColumnType("int");

                    b.Property<double>("Temp")
                        .HasColumnType("float");

                    b.Property<double>("TempMax")
                        .HasColumnType("float");

                    b.Property<double>("TempMin")
                        .HasColumnType("float");

                    b.Property<Guid>("WeatherResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WeatherResponseId")
                        .IsUnique();

                    b.ToTable("Mains");
                });

            modelBuilder.Entity("Sol3.Data.SQL.Weather.Models.Sys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sunrise")
                        .HasColumnType("int");

                    b.Property<int>("Sunset")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("WeatherResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WeatherResponseId")
                        .IsUnique();

                    b.ToTable("Sys");
                });

            modelBuilder.Entity("Sol3.Data.SQL.Weather.Models.Weather", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("WeatherResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Main")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id", "WeatherResponseId");

                    b.HasIndex("WeatherResponseId");

                    b.ToTable("Weather");
                });

            modelBuilder.Entity("Sol3.Data.SQL.Weather.Models.WeatherResponse", b =>
                {
                    b.Property<Guid>("WeatherResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Base")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Dt")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Timezone")
                        .HasColumnType("int");

                    b.Property<int?>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("WeatherResponseId");

                    b.ToTable("WeatherResponse");
                });

            modelBuilder.Entity("Sol3.Data.SQL.Weather.Models.Wind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("Deg")
                        .HasColumnType("int");

                    b.Property<double>("Gust")
                        .HasColumnType("float");

                    b.Property<double>("Speed")
                        .HasColumnType("float");

                    b.Property<Guid>("WeatherResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WeatherResponseId")
                        .IsUnique();

                    b.ToTable("Winds");
                });

            modelBuilder.Entity("Sol3.Data.SQL.Weather.Models.Cloud", b =>
                {
                    b.HasOne("Sol3.Data.SQL.Weather.Models.WeatherResponse", "WeatherResponse")
                        .WithOne("Cloud")
                        .HasForeignKey("Sol3.Data.SQL.Weather.Models.Cloud", "WeatherResponseId")
                        .HasConstraintName("FK_Cloud_WeatherResponse")
                        .IsRequired();

                    b.Navigation("WeatherResponse");
                });

            modelBuilder.Entity("Sol3.Data.SQL.Weather.Models.Coord", b =>
                {
                    b.HasOne("Sol3.Data.SQL.Weather.Models.WeatherResponse", "WeatherResponse")
                        .WithOne("Coord")
                        .HasForeignKey("Sol3.Data.SQL.Weather.Models.Coord", "WeatherResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeatherResponse");
                });

            modelBuilder.Entity("Sol3.Data.SQL.Weather.Models.Main", b =>
                {
                    b.HasOne("Sol3.Data.SQL.Weather.Models.WeatherResponse", "WeatherResponse")
                        .WithOne("Main")
                        .HasForeignKey("Sol3.Data.SQL.Weather.Models.Main", "WeatherResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeatherResponse");
                });

            modelBuilder.Entity("Sol3.Data.SQL.Weather.Models.Sys", b =>
                {
                    b.HasOne("Sol3.Data.SQL.Weather.Models.WeatherResponse", "WeatherResponse")
                        .WithOne("Sys")
                        .HasForeignKey("Sol3.Data.SQL.Weather.Models.Sys", "WeatherResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeatherResponse");
                });

            modelBuilder.Entity("Sol3.Data.SQL.Weather.Models.Weather", b =>
                {
                    b.HasOne("Sol3.Data.SQL.Weather.Models.WeatherResponse", "WeatherResponse")
                        .WithMany("Weathers")
                        .HasForeignKey("WeatherResponseId")
                        .HasConstraintName("FK_Weather_WeatherResponse")
                        .IsRequired();

                    b.Navigation("WeatherResponse");
                });

            modelBuilder.Entity("Sol3.Data.SQL.Weather.Models.Wind", b =>
                {
                    b.HasOne("Sol3.Data.SQL.Weather.Models.WeatherResponse", "WeatherResponse")
                        .WithOne("Wind")
                        .HasForeignKey("Sol3.Data.SQL.Weather.Models.Wind", "WeatherResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeatherResponse");
                });

            modelBuilder.Entity("Sol3.Data.SQL.Weather.Models.WeatherResponse", b =>
                {
                    b.Navigation("Cloud");

                    b.Navigation("Coord");

                    b.Navigation("Main");

                    b.Navigation("Sys");

                    b.Navigation("Weathers");

                    b.Navigation("Wind");
                });
#pragma warning restore 612, 618
        }
    }
}
