// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeatherStation.Data;

#nullable disable

namespace WeatherStation.Data.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20260703011828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeatherStation.Data.Entities.WeatherObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<double?>("DewpointF")
                        .HasColumnType("double precision");

                    b.Property<double?>("FeelsLikeF")
                        .HasColumnType("double precision");

                    b.Property<int?>("HumidityPct")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<decimal?>("PrecipInPerHr")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("PressureInHg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double?>("TempF")
                        .HasColumnType("double precision");

                    b.Property<double?>("UvIndex")
                        .HasColumnType("double precision");

                    b.Property<int?>("WindDirDeg")
                        .HasColumnType("integer");

                    b.Property<double?>("WindGustMph")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeedMph")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ObservedAtUtc")
                        .IsUnique();

                    b.ToTable("WeatherObservations");
                });
#pragma warning restore 612, 618
        }
    }
}
