// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeatherStation.Data;

#nullable disable

namespace WeatherStation.Data.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    partial class WeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeatherStation.Data.Entities.ForecastObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<double?>("DewpointF")
                        .HasColumnType("double precision");

                    b.Property<double?>("FeelsLikeF")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ForecastForUtc")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("HumidityPct")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("LocationKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("citra");

                    b.Property<decimal?>("PrecipInPerHr")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("PressureInHg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<double?>("TempF")
                        .HasColumnType("double precision");

                    b.Property<double?>("UvIndex")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindGustMph")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeedMph")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LocationKey", "IssuedAtUtc", "ForecastForUtc")
                        .IsUnique();

                    b.ToTable("ForecastObservations", (string)null);
                });

            modelBuilder.Entity("WeatherStation.Data.Entities.WeatherObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<double?>("DewpointF")
                        .HasColumnType("double precision");

                    b.Property<double?>("FeelsLikeF")
                        .HasColumnType("double precision");

                    b.Property<int?>("HumidityPct")
                        .HasColumnType("integer");

                    b.Property<string>("LocationKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("citra");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<decimal?>("PrecipInPerHr")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("PressureInHg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double?>("TempF")
                        .HasColumnType("double precision");

                    b.Property<double?>("UvIndex")
                        .HasColumnType("double precision");

                    b.Property<int?>("WindDirDeg")
                        .HasColumnType("integer");

                    b.Property<double?>("WindGustMph")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeedMph")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LocationKey", "ObservedAtUtc")
                        .IsUnique();

                    b.ToTable("WeatherObservations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
